version = 0.1

[dev.deploy.parameters]
stack_name = "ow-tokenization-dev"
region = "us-east-1"
s3_bucket = "ow-protocol-artifacts"
s3_prefix = "dev/tokenization"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Environment=dev",
    "DbSecretsName='/rev/dev/db-secret'",
    "DatabaseName=account_abstraction_dev_db",
    "PrivateSubnets=/dev-stage/network/private-subnet-ids",
    "DatabaseAccessSecurityGroup=/dev/database/access-security-group-id",
    "AaTxRequestQueueUrl=/account-abstraction/dev/sqs/standard-tx-signer/url",
    "AaTxRequestQueueArn=/account-abstraction/dev/sqs/standard-tx-signer/arn",
    "AaTxRequestQueueMessageGroupId=/account-abstraction/dev/sqs/standard-tx-signer/message-group-id",

    "TokenizationQueueName=ow-tokenization-dev.fifo",
    "TokenizationDlqName=ow-tokenization-dev-dlq.fifo",
]

[stage.deploy.parameters]
stack_name = "ow-tokenization-stage"
region = "us-east-1"
s3_bucket = "ow-protocol-artifacts"
s3_prefix = "stage"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Environment=stage",
    "DbSecretsName='/rev/stage/db-secret'",
    "DatabaseName=account_abstraction_stage_db",
    "PrivateSubnets=/dev-stage/network/private-subnet-ids",
    "DatabaseAccessSecurityGroup=/stage/database/access-security-group-id",
    "AaTxRequestQueueUrl=/account-abstraction/stage/sqs/standard-tx-signer/url",
    "AaTxRequestQueueArn=/account-abstraction/stage/sqs/standard-tx-signer/arn",
    "AaTxRequestQueueMessageGroupId=/account-abstraction/stage/sqs/standard-tx-signer/message-group-id",

    "TokenizationQueueName=ow-tokenization-stage.fifo",
    "TokenizationDlqName=ow-tokenization-stage-dlq.fifo",

]

[prod.deploy.parameters]
stack_name = "ow-tokenization-prod"
region = "us-east-1"
s3_bucket = "ow-protocol-artifacts-prod"
s3_prefix = "prod"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "Environment=prod",
    "DbSecretsName='/rev/prod/db-secret'",
    "DatabaseName=account_abstraction_prod_db",
    "PrivateSubnets=/prod/network/private-subnet-ids",
    "DatabaseAccessSecurityGroup=/prod/database/access-security-group-id",
    "AaTxRequestQueueUrl=/account-abstraction/prod/sqs/standard-tx-signer/url",
    "AaTxRequestQueueArn=/account-abstraction/prod/sqs/standard-tx-signer/arn",
    "AaTxRequestQueueMessageGroupId=/account-abstraction/prod/sqs/standard-tx-signer/message-group-id",

    "TokenizationQueueName=ow-tokenization-prod.fifo",
    "TokenizationDlqName=ow-tokenization-prod-dlq.fifo",

]
