# TODO: fill in official OWARD indexers
[indexers.prod]
registry_indexer_url = "re prod"
agreements_indexer_url = "ag prod"

[indexers.stage]
registry_indexer_url = "re stage"
agreements_indexer_url = "ag stage"

[indexers.dev]
registry_indexer_url = "re dev"
agreements_indexer_url = "ag dev"
